## https://docs.docker.com/compose/
## https://docs.docker.com/compose/compose-file/
version: "3.3"


services:
  influxdb:
    ## https://hub.docker.com/_/influxdb
    image: influxdb:1.8-alpine
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    #volumes:
    #- /srv/docker/influxdb/data:/var/lib/influxdb
    environment:
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
      - INFLUXDB_DB=mqtt
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=root
      - INFLUXDB_LOGGING_LEVEL=debug


  chronograf:
    image: chronograf:alpine
    ports:
      - "8888:8888"
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=root
      - INFLUXDB_PASSWORD=root


  mqtt:
    image: eclipse-mosquitto:1.6
    #volumes:
      #- ./config/:/mosquitto/config/:ro
      #- ./data/:/mosquitto/data/:rw
      #- ./log/:/mosquitto/log/:rw
    ports:
      - "1883:1883"
